### ISSUE TITLE
isset is faster than array_key_exists

### ISSUE THREAD

**Issue by lloydzhou** [bephp/router#11]
http://stackoverflow.com/questions/6337893/why-is-array-key-exists-1000x-slower-than-isset-on-referenced-arrays

**Comment by yarcowang** [comment]
Hey, 哥们, 不是很明白.

```
这里需要说明一下的是，由于存储的数据结构不一样，这个控制器没有最坏情况这个说法查找第一个路由和最后一个路由时间复杂度是一样的。
上表的数据也证实了O(log n)复杂度会比O(n)复杂度在时间上少好多，是数量级的差距。
```

一般路由内部存储的难道不是 hash 表吗?

**Comment by lloydzhou** [comment]
@yarcowang  这里说的是在判断某一个key是否在一个array里面的时候，使用isset快还是array_key_exists快的问题。

并不是在讨论你说的存储路由的数据结构的问题

**Comment by yarcowang** [comment]
@lloydzhou isset 和 array_key_exists 比较很早就有人做过测试了, 证明 isset 快. 虽然没去看原理. 但我觉得语言层次的东西不需要太深入. 如果确实存在实现差异, 那肯定也是某种需要...否则一样的需求, 一个实现快一个实现慢, 岂不是很不合理?

我以为你这个 issue 是讨论一般的问题.

**Comment by lloydzhou** [comment]
我当时也就是自己记录一下。没想到，让你误解了。我这就关掉

**Comment by yarcowang** [comment]
挺好的 其实. 同行交流.
