### ISSUE TITLE
这个包是否支持判断GET、POST、PUT、DELETE 等常用的请求？

### ISSUE THREAD

**Issue by liuyami** [bephp/router#12]
这个如果支持，请教如何做，非常感谢。

**Comment by liuyami** [comment]
update:眼花了，看到中文文档有介绍了，
顺便问一下是否支持 Group 定义？
例如我有个前缀都是 /user 的，后面有一系列的 /user/profile , /user/oooo 等等

**Comment by lloydzhou** [comment]
抱歉，没有提供group的功能。

你能给一个使用group的测试用例或者使用场景吗？

**Comment by liuyami** [comment]
hi,感谢你的回复

group功能非必须的，只是如果有，可以直接绑定到一个控制器上，例如 /Product 绑定到一个ProductController 上，访问/Product/category ，那么可以自动到这个控制器方法上，也可以在这个group指定  category 到哪个方法，我不太记得是在哪个route package  有这个功能，只是觉得挺方便的。

**Comment by lloydzhou** [comment]
我增加了group的功能，你看是不是你说的那种功能？

可以使用group或者prefix来调用这个功能：

```
$r->group('/user', function($router){
    $router->get('/:name', array(new Handler(), 'Hello'));
    $router->get('/:name/again', array('Handler', 'hello_again'), 'auth');
});
```

**Comment by lloydzhou** [comment]
后来想了一下，刚刚的那种方式需要写回调函数，可能不是很好，换了一种实现方式：
这样子改动更小

```
$router->group('/user')
    ->get('/:name', array(new Handler(), 'Hello'))
    ->get('/:name/again', array('Handler', 'hello_again'), 'auth');
```

后面如果需要设置另外的group，可以继续这种方式调用。如果不传参数，可以重置group前缀变成空字符串。

**Comment by lloydzhou** [comment]
@liuyami 
我决定使用第二种方式来实现这个功能，一会就合并到master
